config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos do
    member do
      put "like", to: "photos#upvote"
    end
  end

  root "photos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  acts_as_votable
  belongs_to :user
  validates_presence_of :image
  validates :title, presence: true, length: { minimum: 3, maximum: 120 }
  validates :description, presence: true, length: { minimum: 3 }

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.all.order('created_at DESC')
  end

  def show

  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = current_user.photos.build(photo_params)

    if @photo.save
      flash[:success] = "Photo has been posted!"
      redirect_to @photo
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @photo.update(photo_params)
      flash[:success] = "Photo successfully updated."
      redirect_to @photo
    else
      render 'edit'
    end
  end

  def destroy
    @photo.destroy
    redirect_to root_path
  end

  def upvote
    @photo.upvote_by current_user
    redirect_to :back
  end


  private

  def photo_params
    params.require(:photo).permit(:title, :description, :image)
  end

  def find_photo
    @photo = Photo.find(params[:id])
  end

  def require_same_user
    if current_user != @photo.user
      flash[:danger] = 'You can only edit or delete your own photos.'
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">InstaClone</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? %>
            <li><%= link_to 'Add Photo', new_photo_path %></li>
            <li><%= link_to 'Settings', edit_user_registration_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Join', new_user_registration_path%></li>
            <li><%= link_to 'Login', new_user_session_path%></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "InstaClone" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= bootstrap_flash %>
  </div>

    <div class="container">
      <div class="row">

          <%= yield %>


      </div><!--/row-->
    </div> <!-- /container -->

      <footer>
        <div class="container">
          <p>&copy; InstaClone 2016</p>
        </div>
      </footer>



  </body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for @photo, html: { multiplart: true} do |f| %>
  <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<% content_for :title, "Edit #{@photo.title}" %>
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title center">Edit <%= @photo.title %></h3>
    </div>
    <div class="panel-body">
      <div class="center">
        <%= image_tag @photo.image.url(:medium), class: 'img-thumbnail' %>
      </div>
      <%= render 'form' %>

      <%= link_to 'Cancel', photo_path, class:'btn btn-default' %>
    </div>
  </div>

</div>

app/views/photos/index.html.erb
<div class="col-md-12">
<div id="photos" class="transitions-enabled infinite-scroll">
    <% @photos.each do |photo| %>
        <div class="box panel panel-default">
          <%= link_to (image_tag photo.image.url, class: 'img-responsive'), photo_path(photo), class: 'title' %>
          <div class="panel-body">
            <h3 class="center"><%= link_to photo.title, photo_path(photo), class: 'title' %></h3>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<% content_for :title, 'Add Photo' %>
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title center">Add Photo</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>

      <%= link_to 'Back', root_path, class:'btn btn-default' %>
    </div>
  </div>

</div>

app/views/photos/show.html.erb
<% content_for :title, @photo.title %>

  <div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <%= image_tag @photo.image.url, class: 'img-responsive' %>
    <div class="panel-body">
      <h2 class="title"><%= @photo.title%></h2>
      <div class="description"><%= @photo.description %></div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-6">
          <div class="author">by: <%= @photo.user.email %></div>
        </div>
        <div class="col-md-6">
          <div class="btn-group pull-right">
            <%= link_to like_photo_path(@photo), method: :put, class: 'btn btn-default' do %>
                <i class="fa fa-thumbs-o-up"></i> <%= @photo.get_upvotes.size %>
            <% end %>
            <% if user_signed_in? && current_user == @photo.user %>
                <%= link_to 'Edit', edit_photo_path, class: 'btn btn-info' %>
                <%= link_to 'Delete', photo_path, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger'  %>
            <% end %>
          </div>
      </div>
    </div>

    </div>


  </div>

  </div>